--- # deleting file
- hosts: webservers
  user: ansible
  name: my deleting file
  become: yes
  connection: ssh

  tasks:
    - name: deleting a file
      file:
        path: /home/ansible/file10
        state: absent
        
